Repository the-purgatory/sc-web, pull requests merged in 2020-04, with the labels that each got.

#7 Feature/test2
  .github/pr-labeler.yml
  .github/workflows/pr-labeler.yml
  .vscode/settings.json
  README.md
  branch-name-hook.sh
  package.json
  src/index.js
  src/store/index.js
  webpack.config.js
  yarn.lock
Labels: feature

#8 directory structure finalised
  src/components/atoms/index.js
  src/components/molecules/index.js
  src/constants/endpoints.js
  src/index.js
  src/screens/index.js
  src/store/auth/actions.js
  src/store/auth/reducer.js
  src/store/auth/types.js
  src/store/index.js
  src/store/middleware_socket.js
  src/store/reducers.js
  src/styles/index.js
  src/utils/cookies.js
Labels: feature

#9 Feature/theming
  .eslintrc
  package.json
  src/constants/endpoints.js
  src/constants/status.js
  src/index.js
  src/styles/global-styles.js
  src/styles/index.js
  src/styles/theme.js
  src/utils/auth.js
  src/utils/cookies.js
  webpack.config.js
  yarn.lock
Labels: feature

#11 Update README.md
  README.md
Labels: documentation

#12 Update README.md
  README.md
Labels: fix

#10 base-theme :: added theme config
  .vscode/settings.json
  src/App.js
  src/assets/images/logo.svg
  src/components/atoms/Box.js
  src/components/atoms/FlexBox.js
  src/components/atoms/Grid.js
  src/components/atoms/Text.js
  src/components/atoms/index.js
  src/index.html
  src/index.js
  src/screens/Auth.js
  src/screens/index.js
  src/styles/__color.js
  src/styles/__font.js
  src/styles/__general.js
  src/styles/__layout.js
  src/styles/common.js
  src/styles/reset.js
  src/styles/theme.js
Labels: feature

#13 Added authorisation, routing and some structural changes
  .codeclimate.yml
  .eslintrc
  .gitignore
  README.md
  package.json
  src/App.js
  src/assets/images/logo.svg
  src/components/atoms/Box/index.js
  src/components/atoms/Button/index.js
  src/components/atoms/ErrorBox/index.js
  src/components/atoms/FlexBox/index.js
  src/components/atoms/FontIcon/index.js
  src/components/atoms/Grid/index.js
  src/components/atoms/Input/index.js
  src/components/atoms/LinkButton/index.js
  src/components/atoms/Loader/index.js
  src/components/atoms/Logo/index.js
  src/components/atoms/Portal/index.js
  src/components/atoms/Seperator/index.js
  src/components/atoms/Text/index.js
  src/components/atoms/index.js
  src/components/molecules/avatar/index.js
  src/components/molecules/dropdown/index.js
  src/components/molecules/dropdown1/components/Menu.js
  src/components/molecules/dropdown1/components/MenuItem.js
  src/components/molecules/dropdown1/components/Toggle.js
  src/components/molecules/dropdown1/index.js
  src/components/molecules/dropdown1/utils/index.js
  src/components/molecules/index.js
  src/components/organisms/SigninForm/index.js
  src/components/organisms/SignupForm/index.js
  src/components/organisms/index.js
  src/constants/endpoints.js
  src/index.html
  src/screens/Auth.js
  src/screens/auth/components/form-container/index.js
  src/screens/auth/index.js
  src/screens/home/components/content-panel/index.js
  src/screens/home/components/left-panel/index.js
  src/screens/home/components/navigation-menu/index.js
  src/screens/home/components/right-panel/index.js
  src/screens/home/index.js
  src/store/auth/actions.js
  src/store/auth/reducer.js
  src/store/auth/types.js
  src/styles/__color.js
  src/styles/__font.js
  src/styles/__general.js
  src/styles/__layout.js
  src/styles/common.js
  src/utils/auth.js
  src/utils/image.js
  src/utils/index.js
  src/utils/validator.js
  webpack.config.js
  yarn.lock
Labels: feature
