Repository the-purgatory/sc-web, pull requests merged in 2020-03, with the labels that each got.

#1 edited codeclimate config
  .codeclimate.yml
  .gitignore
Labels: fix

#2 test commit
  src/index.js
Labels: misc

#3 test commit
  src/index.js
Labels: feature

#4 branch name hook
  branch-name-hook.sh
  package.json
Labels: feature

#5 branch name hook
  branch-name-hook.sh
Labels: feature
